    drop table car if exists;

    drop table driver if exists;

    drop table driver_car if exists;

    drop table manufacturer if exists;

    create table car (
        id bigint generated by default as identity,
        convertible boolean,
        date_created timestamp not null,
        deleted boolean not null,
        engine_type varchar(255),
        license_plate varchar(255),
        rating float,
        seat_count integer,
        manufacturer bigint,
        primary key (id)
    );

    create table driver (
        id bigint generated by default as identity,
        coordinate binary(255),
        date_coordinate_updated timestamp,
        date_created timestamp not null,
        deleted boolean not null,
        online_status varchar(255) not null,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );

    create table driver_car (
        id bigint generated by default as identity,
        car_id bigint,
        driver_id bigint,
        primary key (id)
    );

    create table manufacturer (
        id bigint generated by default as identity,
        date_created timestamp not null,
        name varchar(255),
        primary key (id)
    );

    alter table driver
        add constraint uc_username unique (username);

    alter table driver_car
        add constraint UK_153ddux4mmmqyh1kfwle4brs0 unique (car_id);

    alter table driver_car
        add constraint UK_j0fsjuo02qmg7xtja835naipp unique (driver_id);

    alter table car
        add constraint FKh7sqtdc5ahndg7q5h7gdsc4xm
        foreign key (manufacturer)
        references manufacturer;


